[book]
authors = ["John Socha-Leialoha"]
language = "en"
src = "src"
title = "OpenLCB Technical Introduction"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
